# -*- coding: utf-8 -*-
"""Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1deKg5ivlVUkpciERxz7LaKVNQvZ71zhP
"""

import numpy as np

import pandas as pd

import difflib

from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.metrics.pairwise import cosine_similarity

# Step 1: Load Data


df = pd.read_csv('netflix_titles.csv')

df.head()

df.shape

print(df.columns)

# Step 2: Feature Selection


selected_features = ['listed_in','rating','cast','director','description','type']

print(selected_features)

# Step 3: Handle Missing Values


for feature in selected_features:
  df[feature] = df[feature].fillna('')

# Step 4: Combine Selected Features into a Single Text Column


combined_features = (df['listed_in'] + ' ' +
                     df['rating'] + ' ' +
                     df['cast'] + ' ' +
                     df['director'] + ' ' +
                     df['description'] + ' ' +
                     df['type'])

print(combined_features)

# Step 5: Convert Text Data to Feature Vectors


vectorizer = TfidfVectorizer()

feature_vectors = vectorizer.fit_transform(combined_features)

print(feature_vectors)

# Step 6: Calculate Cosine Similarity


similarity_matrix = cosine_similarity(feature_vectors)

print(similarity_matrix)

print(similarity_matrix.shape)

# Step 7: Create a List of Content Titles


list_of_all_titles = df['title'].tolist()

print(list_of_all_titles)

# Step 8: User Input for Content Recommendation


content_name = input(' Enter your favourite Content name : ')

# Step 9: Find Closest Matching Title


find_close_match = difflib.get_close_matches(content_name, list_of_all_titles)

print(find_close_match)

close_match = find_close_match[0]

print(close_match)

# Step 10: Get Index of the Selected Content


index_of_the_content = df[df.title == close_match]['show_id'].values[0]

print(index_of_the_content)

index_mapping = {idx: i for i, idx in enumerate(df.show_id)}

#Get the alphanumeric index

alphanumeric_index = df[df.title == close_match]['show_id'].values[0]

# Get the numeric index of the content

index_of_the_content = index_mapping[alphanumeric_index]

print(f"The alphanumeric index {alphanumeric_index} corresponds to the numerical index : {index_of_the_content}")

# Step 11: Get Similarity Score


similarity_score = list(enumerate(similarity_matrix[index_of_the_content]))

similarity_score = [(list(index_mapping.keys())[idx], score) for idx, score in similarity_score]

print(similarity_score)

len(similarity_score)

# Step 12: Sort Content Based on Similarity Score


sorted_similar_content = sorted(similarity_score, key = lambda x:x[1], reverse = True)

print(sorted_similar_content)

# Step 13: Display Recommended Content


print('Content suggested for you : \n')

i = 1

for movie in sorted_similar_content:
  alphanumeric_index = movie[0]
  title_from_index = df[df['show_id'] == alphanumeric_index]['title'].values[0]
  if (i<=30):
    print(i, '.',title_from_index)
    i+=1

